import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "../components/navbar/Nav";
import ReduxProvider from "@/redux/ReduxProvider";
import ProfileNav from "@/components/navbar/ProfileNav";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Toast from "@/components/popups/Toast";
import { BASE_URL } from "@/utils/constants";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"], weight: ["400", "700", "200"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="dns-prefetch" href={`${BASE_URL}`} />
        <link rel="preconnect" href={`${BASE_URL}`} />
      </head>
      <body className={inter.className}>
        <ReduxProvider>
          <Toast />
          <Nav>
            <ProfileNav />
          </Nav>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
