import React from "react";
import AuthProvider from "../utils/AuthProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "../components/navbar/Nav";
import ReduxProvider from "@/redux/ReduxProvider";
import ProfileNav from "@/components/navbar/ProfileNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
         <ReduxProvider>
         <Nav >
          <ProfileNav/>
         </Nav>
          {children}
         </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
